apiVersion: v1
kind: Service
metadata:
  name: lifecycle-tester
  annotations:
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lifecycle-tester
  type: ClusterIP
